#!/usr/bin/env ruby

require 'net/http'
require 'json'

uri = URI.parse('https://api.icndb.com/jokes/random?limitTo=[nerdy]')
response = Net::HTTP.get(uri)
joke = JSON.parse(response)["value"]["joke"]

puts joke
