#!/bin/sh

set -e

PATH="/usr/local/bin:$PATH"
dir="$(git rev-parse --show-toplevel)"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
  "${CTAGS:-ctags}" --tag-relative -R -L - -f"$dir/$$.tags"
mv "$dir/$$.tags" "$dir/tags"
