#!/bin/sh

repo_name=$1
token=$GITLABPR
url=$GITLAB_URL

test -z $repo_name && echo "Repo name required." 1>&2 && exit 1

curl -H "Content-Type:application/json" https://$url/api/v4/projects?private_token=$token -d "{ \"name\": \"$repo_name\" }"
